// Generated by CoffeeScript 1.10.0
(function() {
  var counter, element, repeatDelay, timer;

  repeatDelay = function(ms, func) {
    return setInterval(func, ms);
  };

  counter = 4;

  element = document.querySelector('#counter');

  timer = repeatDelay(1000, function() {
    if (--counter < 0) {
      clearInterval(timer);
      return element.innerText = '';
    } else {
      return element.innerText = '- ' + counter;
    }
  });

}).call(this);

//# sourceMappingURL=notification.js.map
